FROM mageia:latest

ARG PROJECT_NAME=datalake
ARG MAGE_CODE_PATH=/mage_app
ARG USER_CODE_PATH=${MAGE_CODE_PATH}/${PROJECT_NAME}

WORKDIR ${MAGE_CODE_PATH}

COPY ${PROJECT_NAME} ${PROJECT_NAME}

ENV USER_CODE_PATH=${USER_CODE_PATH}

RUN apt-get update -y && \
  apt-get install -y openjdk-11-jdk wget

RUN pip3 install -r ${USER_CODE_PATH}/requirements.txt --no-cache-dir
RUN python3 /app/install_other_dependencies.py --path ${USER_CODE_PATH}

ENV PYTHONPATH="${PYTHONPATH}:/home/src"

CMD ["/bin/sh", "-c", "/app/run_app.sh"]
